trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  veracodeAppProfile: testetemplate.$(Build.DefinitionName)
  caminhoPacote: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  enableCustomProcessTemplate: true
  customWorkItemType: 'Vulnerabilidades'  # Tipo do work item criado, ex.: Bug, Epic, Issue etc.
  customPTActiveStatus: 'Active'         # Status para indicar que o item está "em progresso"
  customPTNewStatus: 'New'               # Status para indicar um item "novo"
  customPTResolvedStatus: 'Resolved'     # Status para indicar um item "resolvido"
  customPTCloseStatus: 'Closed'          # Status para indicar que o item está "concluído"

stages:
- stage: BuildAndScan
  jobs:
  - job: BuildAndScanJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Agent.BuildDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(caminhoPacote)'
        replaceExistingArchive: true
      displayName: 'Criando pacote para análise'

    # Veracode SCA
    - script: |
        curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan app
      env:
        SRCCLR_API_TOKEN: $(SRCCLR_TOKEN)
      displayName: 'Veracode SCA Scan'

    - script: |
        curl -O -L https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      displayName: 'Download Pipeline Scanner'

    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: 'pipeline-scan-LATEST.zip'
        destinationFolder: '$(Build.ArtifactStagingDirectory)'
        cleanDestinationFolder: false

    - script: |
        java -jar $(Build.ArtifactStagingDirectory)/pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) --file '$(caminhoPacote)' --issue_details true
      displayName: 'Veracode Pipeline Scan'
      continueOnError: true

    - task: Veracode@3
      inputs:
        ConnectionDetailsSelection: 'Credentials'
        apiId: '$(VERACODE_API_ID)'
        apiKey: '$(VERACODE_API_KEY)'
        veracodeAppProfile: '$(veracodeAppProfile)'
        version: '$(build.buildNumber)'
        filepath: '$(caminhoPacote)'
        createSandBox: false
        createProfile: true
        failTheBuildIfVeracodeScanDidNotInitiate: false
        scanStatusCheckInterval: '60'
        importResults: true
        failBuildOnPolicyFail: false
      displayName: 'Veracode SAST'

    - task: Veracode Flaw Importer@3
      inputs:
        ConnectionDetailsSelection: 'Credentials'
        apiId: '$(VERACODE_API_ID)'
        apiKey: '$(VERACODE_API_KEY)'
        veracodeAppProfile: '$(veracodeAppProfile)'
        sandboxName: 
        scanType: 'Static, SCA'
        importType: 'All Flaws'
        customWorkItemTemplateName: 'Agile-Security-Process'
        workItemType: 'Vulnerabilidades'
        area: 'template_personalizado'
        overwriteAreaPathInWorkItemsOnImport: true
        iterationPath: 'template_personalizado'
        overwriteIterationPath: true
        flawImportLimit: '1000'
      displayName: 'Veracode Import Flaws'
  
