name: Veracode Template v3

on:
  workflow_call:

env:
  PROJECT: ${{ inputs.project_veracode }}
  ENVIRONMENT: ${{ inputs.environment }}
  SRCCLR_WORKSPACE_SLUG: ${{ inputs.SRCCLR_WORKSPACE_SLUG }}

jobs:
  veracode-sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar Veracode SCA Scan
        uses: veracode/veracode-sca@v2.1.10
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          SRCCLR_WORKSPACE_SLUG: ${{ secrets.SRCCLR_WORKSPACE_SLUG }}
