name: Veracode SCA Scan

on:
  workflow_call:
    secrets:
      SRCCLR_WORKSPACE_SLUG:
        required: true

jobs:
  SCA:
    name: SCA
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Executar Veracode SCA
        #continue-on-error: true
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA }}
          SRCCLR_WORKSPACE_SLUG: ${{ secrets.SRCCLR_WORKSPACE_SLUG }}
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan --update-advisor --allow-dirty
