name: Veracode SCA Scan

on:
  workflow_call:
    secrets:
      SRCCLR_WORKSPACE_SLUG:
        required: true

jobs:
  veracode-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Executar Veracode SCA Scan
        uses: veracode/veracode-sca@v2.1.10
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA }}
          SRCCLR_WORKSPACE_SLUG: ${{ secrets.SRCCLR_WORKSPACE_SLUG }}
        with:
          quick: true
          store-results-json: false # <-- adicionar esta linha
